# Generated by Django 3.2.5 on 2021-08-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210817_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
